### ISSUE TITLE
When we try to check in it fails

### ISSUE THREAD

**Issue by DalpheSDC** [jessehouwing/azure-pipelines-tfvc-tasks#88]
Preview 2 on Azure devops Server 2019
```
019-10-23T10:06:48.7896128Z ##[section]Starting: Check changes into source control
2019-10-23T10:06:48.7901437Z ==============================================================================
2019-10-23T10:06:48.7901677Z Task         : TFVC - Check-in changes 
2019-10-23T10:06:48.7901783Z Description  : Checks in any files changed in the repository.
2019-10-23T10:06:48.7901892Z Version      : 2.0.7
2019-10-23T10:06:48.7901969Z Author       : Jesse Houwing
2019-10-23T10:06:48.7902075Z Help         : [More Information](https://github.com/jessehouwing/azure-pipelines-tfvc-tasks/wiki/Check-in)
2019-10-23T10:06:48.7902171Z ==============================================================================
2019-10-23T10:06:52.3043448Z ##[error]Exception calling "EnsureUpdateWorkspaceInfoCache" with "2" argument(s): "The string must have at least one character.
Parameter name: ownerName"
2019-10-23T10:06:52.3773621Z ##[section]Finishing: Check changes into source control


Exception calling "EnsureUpdateWorkspaceInfoCache" with "2" argument(s): "The string must have at least one character
```

**Comment by jessehouwing** [comment]
I need more data than that. can you run a build with diagnostics turned on and share the data? 
ca you share a screenshot of the task UI/YAML?

**Comment by jessehouwing** [comment]
And the exact agent version?

**Comment by jessehouwing** [comment]
It looks like `$versionControlServer.AuthorizedUser` is returning nothing, that can't be good.

**Comment by DalpheSDC** [comment]
It is UI version and the agent version is 

2.154.3

The Visual studio version on the server is VS 2017 Enterprise

**Comment by DalpheSDC** [comment]
run with debug
2019-10-23T12:20:25.6430051Z ##[debug]Evaluating condition for step: 'Check changes into source control'
2019-10-23T12:20:25.6431732Z ##[debug]Evaluating: succeeded()
2019-10-23T12:20:25.6432078Z ##[debug]Evaluating succeeded:
2019-10-23T12:20:25.6432758Z ##[debug]=> True
2019-10-23T12:20:25.6433255Z ##[debug]Result: True
2019-10-23T12:20:25.6433753Z ##[section]Starting: Check changes into source control
2019-10-23T12:20:25.6439142Z ==============================================================================
2019-10-23T12:20:25.6439437Z Task         : TFVC - Check-in changes 
2019-10-23T12:20:25.6439517Z Description  : Checks in any files changed in the repository.
2019-10-23T12:20:25.6439607Z Version      : 2.0.7
2019-10-23T12:20:25.6439716Z Author       : Jesse Houwing
2019-10-23T12:20:25.6439796Z Help         : [More Information](https://github.com/jessehouwing/azure-pipelines-tfvc-tasks/wiki/Check-in)
2019-10-23T12:20:25.6440123Z ==============================================================================
2019-10-23T12:20:26.6510663Z ##[debug]VstsTaskSdk 0.11.0 commit 7ff27a3e0bdd6f7b06690ae5f5b63cb84d0f23f4
2019-10-23T12:20:26.7572083Z ##[debug]Entering script TfvcCheckin.v3.ps1
2019-10-23T12:20:26.7805709Z ##[debug]INPUT_COMMENT: 'Jndata'
2019-10-23T12:20:26.7902123Z ##[debug]INPUT_INCLUDENOCICOMMENT: 'true'
2019-10-23T12:20:26.7902665Z ##[debug] Converted to bool: True
2019-10-23T12:20:26.7906450Z ##[debug]INPUT_ITEMSPEC: 'D:/TFS/PARM/*.PARM'
2019-10-23T12:20:26.7934551Z ##[debug]INPUT_RECURSION: 'Full'
2019-10-23T12:20:26.7959376Z ##[debug]INPUT_CONFIRMUNDERSTAND: 'true'
2019-10-23T12:20:26.7976647Z ##[debug] Converted to bool: True
2019-10-23T12:20:26.8041888Z ##[debug]INPUT_OVERRIDEPOLICY: 'true'
2019-10-23T12:20:26.8042330Z ##[debug] Converted to bool: True
2019-10-23T12:20:26.8042468Z ##[debug]INPUT_OVERRIDEPOLICYREASON: 'JNData'
2019-10-23T12:20:26.8057907Z ##[debug]INPUT_NOTES: 'Name=JNData'
2019-10-23T12:20:26.8080709Z ##[debug]INPUT_SKIPGATED: 'true'
2019-10-23T12:20:26.8097222Z ##[debug] Converted to bool: True
2019-10-23T12:20:26.8120488Z ##[debug]INPUT_SKIPSHELVESET: 'true'
2019-10-23T12:20:26.8136438Z ##[debug] Converted to bool: True
2019-10-23T12:20:26.8167698Z ##[debug]INPUT_AUTODETECTADDS: 'true'
2019-10-23T12:20:26.8174931Z ##[debug] Converted to bool: True
2019-10-23T12:20:26.8196821Z ##[debug]INPUT_AUTODETECTDELETES: 'true'
2019-10-23T12:20:26.8214997Z ##[debug] Converted to bool: True
2019-10-23T12:20:26.8238183Z ##[debug]INPUT_BYPASSGATEDCHECKIN: 'false'
2019-10-23T12:20:26.8255608Z ##[debug] Converted to bool: False
2019-10-23T12:20:26.8289546Z ##[debug]Loading module from path 'D:\TFS\A3\w\_tasks\tf-vc-checkin_31f040e5-e040-4556-878a-59a47c7128bd\2.0.7\ps_modules\VstsTfvcShared\VstsTfvcShared.psm1'.
2019-10-23T12:20:26.8635529Z ##[debug]Setting default assembly locations
2019-10-23T12:20:26.9981187Z ##[debug]Trying: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Microsoft.TeamFoundation.Client.dll
2019-10-23T12:20:27.0211705Z ##[debug]Loading assembly: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Microsoft.TeamFoundation.Client.dll
2019-10-23T12:20:27.0399465Z ##[debug]Setting default assembly locations
2019-10-23T12:20:27.0889481Z ##[debug]Trying: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Microsoft.TeamFoundation.Common.dll
2019-10-23T12:20:27.1040854Z ##[debug]Loading assembly: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Microsoft.TeamFoundation.Common.dll
2019-10-23T12:20:27.1144887Z ##[debug]Setting default assembly locations
2019-10-23T12:20:27.1657040Z ##[debug]Trying: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Microsoft.TeamFoundation.VersionControl.Client.dll
2019-10-23T12:20:27.3267215Z ##[debug]Loading assembly: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Microsoft.TeamFoundation.VersionControl.Client.dll
2019-10-23T12:20:27.3720361Z ##[debug]Setting default assembly locations
2019-10-23T12:20:27.4315632Z ##[debug]Trying: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Microsoft.TeamFoundation.WorkItemTracking.Client.dll
2019-10-23T12:20:27.4497766Z ##[debug]Loading assembly: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Microsoft.TeamFoundation.WorkItemTracking.Client.dll
2019-10-23T12:20:27.4539380Z ##[debug]Setting default assembly locations
2019-10-23T12:20:27.5025441Z ##[debug]Trying: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Microsoft.TeamFoundation.Diff.dll
2019-10-23T12:20:27.5089598Z ##[debug]Loading assembly: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Microsoft.TeamFoundation.Diff.dll
2019-10-23T12:20:27.5232955Z ##[debug]Exporting function 'Write-Message'.
2019-10-23T12:20:27.5249613Z ##[debug]Exporting function 'Invoke-DisposeSourceProvider'.
2019-10-23T12:20:27.5265004Z ##[debug]Exporting function 'Get-SourceProvider'.
2019-10-23T12:20:27.5280614Z ##[debug]Exporting function 'AutoPend-WorkspaceChanges'.
2019-10-23T12:20:27.5295132Z ##[debug]Exporting function 'Convert-ToItemSpecs'.
2019-10-23T12:20:27.5309044Z ##[debug]Exporting function 'Find-VisualStudio'.
2019-10-23T12:20:27.5323396Z ##[debug]The 'AutoPend-WorkspaceChanges' command in the VstsTfvcShared' module was imported, but because its name does not include an approved verb, it might be difficult to find. For a list of approved verbs, type Get-Verb.
2019-10-23T12:20:27.5337860Z ##[debug]Importing function 'AutoPend-WorkspaceChanges'.
2019-10-23T12:20:27.5397849Z ##[debug]Importing function 'Convert-ToItemSpecs'.
2019-10-23T12:20:27.5399556Z ##[debug]Importing function 'Find-VisualStudio'.
2019-10-23T12:20:27.5399825Z ##[debug]Importing function 'Get-SourceProvider'.
2019-10-23T12:20:27.5399986Z ##[debug]Importing function 'Invoke-DisposeSourceProvider'.
2019-10-23T12:20:27.5400140Z ##[debug]Importing function 'Write-Message'.
2019-10-23T12:20:27.5415592Z ##[debug]Importing modules
2019-10-23T12:20:27.5431159Z ##[debug]Entering script TfvcCheckin.v3.ps1
2019-10-23T12:20:27.5921297Z ##[debug]Entering Get-SourceProvider
2019-10-23T12:20:27.6021997Z ##[debug]SYSTEM_TEAMFOUNDATIONCOLLECTIONURI: 'https://tfs-prod.tst-ressource.sdc.dk/tfs/PRODCollection/'
2019-10-23T12:20:27.6655072Z ##[debug]Entering Get-VstsTfsClientCredentials.
2019-10-23T12:20:27.6796502Z ##[debug] OMDirectory: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\'
2019-10-23T12:20:27.6932544Z ##[debug]ENDPOINT_URL_SystemVssConnection: 'https://tfs-prod.tst-ressource.sdc.dk/tfs/PRODCollection/'
2019-10-23T12:20:27.6955676Z ##[debug]ENDPOINT_AUTH_SystemVssConnection: '********'
2019-10-23T12:20:27.6977653Z ##[debug]ENDPOINT_DATA_SystemVssConnection (empty)
2019-10-23T12:20:27.7196301Z ##[debug]Entering Get-OMType.
2019-10-23T12:20:27.7213216Z ##[debug] TypeName: 'Microsoft.TeamFoundation.Client.TfsClientCredentials'
2019-10-23T12:20:27.7227327Z ##[debug] OMKind: 'ExtendedClient'
2019-10-23T12:20:27.7243324Z ##[debug] OMDirectory: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\'
2019-10-23T12:20:27.7285228Z ##[debug] Require: 'True'
2019-10-23T12:20:27.7303840Z ##[debug]Testing whether type can be loaded: 'Microsoft.TeamFoundation.Client.TfsClientCredentials'
2019-10-23T12:20:27.7354816Z ##[debug]The type was loaded successfully.
2019-10-23T12:20:27.7388357Z ##[debug]Leaving Get-OMType.
2019-10-23T12:20:27.8081949Z ##[debug]Leaving Get-VstsTfsClientCredentials.
2019-10-23T12:20:28.6088129Z ##[debug]Entering Invoke-DisposeSourceProvider
2019-10-23T12:20:28.6147817Z ##[debug]Disposing tfsTeamProjectCollection
2019-10-23T12:20:28.6199524Z ##[debug]Leaving Invoke-DisposeSourceProvider
2019-10-23T12:20:28.6218530Z ##[debug]Leaving Get-SourceProvider
2019-10-23T12:20:28.6258708Z ##[debug]Entering Invoke-DisposeSourceProvider
2019-10-23T12:20:28.6273936Z ##[debug]Leaving Invoke-DisposeSourceProvider
2019-10-23T12:20:28.6328786Z ##[debug]Caught exception from task script.
2019-10-23T12:20:28.6363424Z ##[debug]Error record:
2019-10-23T12:20:28.7021757Z ##[debug]Get-SourceProvider : Exception calling "EnsureUpdateWorkspaceInfoCache" with "2" argument(s): "The string must have at least one character.
2019-10-23T12:20:28.7034525Z ##[debug]Parameter name: ownerName"
2019-10-23T12:20:28.7044588Z ##[debug]At D:\TFS\A3\w\_tasks\tf-vc-checkin_31f040e5-e040-4556-878a-59a47c7128bd\2.0.7\TfvcCheckin.v3.ps1:176 char:17
2019-10-23T12:20:28.7054047Z ##[debug]+     $provider = Get-SourceProvider
2019-10-23T12:20:28.7063581Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~
2019-10-23T12:20:28.7073490Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [Get-SourceProvider], MethodInvocationException
2019-10-23T12:20:28.7082655Z ##[debug]    + FullyQualifiedErrorId : ArgumentException,Get-SourceProvider
2019-10-23T12:20:28.7092179Z ##[debug] 
2019-10-23T12:20:28.7108417Z ##[debug]Script stack trace:
2019-10-23T12:20:28.7142817Z ##[debug]at Get-SourceProvider, D:\TFS\A3\w\_tasks\tf-vc-checkin_31f040e5-e040-4556-878a-59a47c7128bd\2.0.7\ps_modules\VstsTfvcShared\VstsTfvcShared.psm1: line 124
2019-10-23T12:20:28.7151921Z ##[debug]at <ScriptBlock>, D:\TFS\A3\w\_tasks\tf-vc-checkin_31f040e5-e040-4556-878a-59a47c7128bd\2.0.7\TfvcCheckin.v3.ps1: line 176
2019-10-23T12:20:28.7161682Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-10-23T12:20:28.7170808Z ##[debug]at <ScriptBlock>, <No file>: line 22
2019-10-23T12:20:28.7180188Z ##[debug]at <ScriptBlock>, <No file>: line 18
2019-10-23T12:20:28.7189045Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-10-23T12:20:28.7205434Z ##[debug]Exception:
2019-10-23T12:20:28.7284984Z ##[debug]System.Management.Automation.MethodInvocationException: Exception calling "EnsureUpdateWorkspaceInfoCache" with "2" argument(s): "The string must have at least one character.
2019-10-23T12:20:28.7294948Z ##[debug]Parameter name: ownerName" ---> System.ArgumentException: The string must have at least one character.
2019-10-23T12:20:28.7305489Z ##[debug]Parameter name: ownerName
2019-10-23T12:20:28.7314679Z ##[debug]   at Microsoft.VisualStudio.Services.Common.ArgumentUtility.CheckStringForNullOrEmpty(String stringVar, String stringVarName, Boolean trim, String expectedServiceArea)
2019-10-23T12:20:28.7323863Z ##[debug]   at Microsoft.TeamFoundation.VersionControl.Client.Workstation.EnsureUpdateWorkspaceInfoCache(VersionControlServer sourceControl, String ownerName, TimeSpan maxAge)
2019-10-23T12:20:28.7332887Z ##[debug]   at CallSite.Target(Closure , CallSite , Object , Object , Object )
2019-10-23T12:20:28.7342385Z ##[debug]   --- End of inner exception stack trace ---
2019-10-23T12:20:28.7351383Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2019-10-23T12:20:28.7360548Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2019-10-23T12:20:28.7369562Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-10-23T12:20:28.7378897Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-10-23T12:20:28.7387888Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2019-10-23T12:20:28.7397088Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2019-10-23T12:20:28.7406134Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2019-10-23T12:20:28.7415315Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2019-10-23T12:20:28.7424230Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2019-10-23T12:20:28.7671625Z ##[error]Exception calling "EnsureUpdateWorkspaceInfoCache" with "2" argument(s): "The string must have at least one character.
Parameter name: ownerName"
2019-10-23T12:20:28.7681755Z ##[debug]Processed: ##vso[task.logissue type=error]Exception calling "EnsureUpdateWorkspaceInfoCache" with "2" argument(s): "The string must have at least one character.%0D%0AParameter name: ownerName"
2019-10-23T12:20:28.7698285Z ##[debug]Processed: ##vso[task.complete result=Failed]
2019-10-23T12:20:28.8765618Z ##[section]Finishing: Check changes into source control

**Comment by jessehouwing** [comment]
I can't repro this at the moment and don't have a Azure DevOps Server 2019 available with that build agent, so this may take some time for me to fix. I'm sure something has changed in the agent or with Azure DevOps Server 2019, since you're the first to warn me. 

While looking into it I did find an issue with Visual Studio 2019 changes and rolled out a patch. I hope that may also work for you, as I added a piece of code to force authentication. Installing Team Explorer 2019 may also fix this. 

Can you try running the build again with the latest version of the extension (2.2.1)

**Comment by jessehouwing** [comment]
Darn I thought I had just fixed that.

**Comment by DalpheSDC** [comment]
This was with version 2.2.2

**Comment by jessehouwing** [comment]
Looks like the agent didn't pick the latest version of the task, should read `Version      : 2.0.10`

**Comment by jessehouwing** [comment]
Any news @DalpheSDC

**Comment by jessehouwing** [comment]
https://github.com/microsoft/azure-pipelines-task-lib/pull/594
